name: copy_paste
description: Note List

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.2
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  share_plus: ^7.2.1
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_database: ^10.3.5
  firebase_storage: ^11.5.2
  firebase_ui_auth: ^1.10.0
  firebase_ui_oauth_google: ^1.2.14
  flutter_speed_dial: ^7.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
