name: copy_paste
description: Note List

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.9.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_database: ^10.2.6
  firebase_storage: ^11.2.7
  firebase_ui_auth: ^1.8.0
  firebase_ui_oauth_google: ^1.2.11
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
